name: 功能建议
description: 提一个功能需求
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: describe
    attributes:
      label: 功能描述
      description: 你希望增加或改进什么功能
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: 使用场景
      description: 这个功能解决什么问题、在什么场景下用到
  - type: textarea
    id: alternatives
    attributes:
      label: 备选方案
      description: 是否考虑过其他实现方式
